require:
    - rubocop-rake
    - rubocop-minitest

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.2
  Exclude:
  - 'vendor/**/*'

Minitest/MultipleAssertions:
  Enabled: false
